### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Will269269** [axsddlr/civitai_downloader#3]
First and foremost! thank you for creating something simple here for us less savvy API knowledge folks.

Below is the error I get when trying to run "python main.py"

`Request failed with status code 500
Traceback (most recent call last):
  File "J:\Civitai\civitai_downloader\main.py", line 224, in <module>
    asyncio.run(main())
  File "J:\SD-WebUI\Python3.10.6-installed\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "J:\SD-WebUI\Python3.10.6-installed\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "J:\Civitai\civitai_downloader\main.py", line 214, in main
    files_as_objects = await get_all_files()
  File "J:\Civitai\civitai_downloader\main.py", line 201, in get_all_files
    _, _, _, modelver_list = await map_api()
  File "J:\Civitai\civitai_downloader\main.py", line 79, in map_api
    file_type = [model["type"] for model in all_models]
TypeError: 'NoneType' object is not iterable`

Interesting enough I think its part API call fail? and something to do with line 79 "all_models"?
any support would be greatly appreciative!

**Comment by axsddlr** [comment]
api issue, not on script end

**Comment by axsddlr** [comment]
> First and foremost! thank you for creating something simple here for us less savvy API knowledge folks.
> 
> Below is the error I get when trying to run "python main.py"
> 
> `Request failed with status code 500 Traceback (most recent call last): File "J:\Civitai\civitai_downloader\main.py", line 224, in <module> asyncio.run(main()) File "J:\SD-WebUI\Python3.10.6-installed\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "J:\SD-WebUI\Python3.10.6-installed\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "J:\Civitai\civitai_downloader\main.py", line 214, in main files_as_objects = await get_all_files() File "J:\Civitai\civitai_downloader\main.py", line 201, in get_all_files _, _, _, modelver_list = await map_api() File "J:\Civitai\civitai_downloader\main.py", line 79, in map_api file_type = [model["type"] for model in all_models] TypeError: 'NoneType' object is not iterable`
> 
> Interesting enough I think its part API call fail? and something to do with line 79 "all_models"? any support would be greatly appreciative!

api issue, not on script end

**Comment by Will269269** [comment]
Thanks for the speedy replied! you think this is something I can fix or is this more Civitai side?
